#!/usr/bin/env python3
"""
Hackathon-DDL Multi-Platform Scraper
Automatically crawl hackathon data from major platforms and update YAML files.

Supported platforms (priority order):
1. Devpost (https://devpost.com/hackathons)
2. MLH (https://mlh.io/seasons/2026/events)
3. DoraHacks (API)
4. Hackathon.com

Usage:
    python scripts/scraper.py --output data/2026/

Environment variables:
    GITHUB_TOKEN - GitHub token for creating issues on failure
"""

import argparse
import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from urllib.parse import urljoin, urlparse

import yaml


def log(msg: str, level: str = "INFO"):
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    print(f"[{ts}] [{level}] {msg}", flush=True)


def write_yaml(data: list[dict], filepath: Path):
    """Write hackathon data to YAML file with consistent formatting."""
    filepath.parent.mkdir(parents=True, exist_ok=True)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write("# Auto-generated by Hackathon-DDL scraper\n")
        f.write(f"# Updated: {datetime.now(timezone.utc).isoformat()}\n\n")
        yaml.dump(
            data,
            f,
            allow_unicode=True,
            default_flow_style=False,
            sort_keys=False,
            width=120,
        )
    log(f"Written {len(data)} entries to {filepath}")


def scrape_devpost() -> list[dict]:
    """
    Scrape upcoming hackathons from Devpost.
    Returns list of hackathon dicts matching the YAML schema.

    Note: Devpost does not have an official API. This uses their
    public hackathon listing page. Respect rate limits.
    """
    log("Scraping Devpost...")
    results = []

    try:
        import requests
        from bs4 import BeautifulSoup

        url = "https://devpost.com/hackathons"
        headers = {
            "User-Agent": (
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/120.0.0.0 Safari/537.36"
            ),
            "Accept": "text/html,application/xhtml+xml",
        }

        resp = requests.get(url, headers=headers, timeout=30)
        resp.raise_for_status()
        soup = BeautifulSoup(resp.text, "html.parser")

        # Devpost hackathon cards
        for article in soup.find_all("article", class_="challenge-listing"):
            try:
                title_tag = article.find("h3") or article.find("h2")
                if not title_tag:
                    continue
                title = title_tag.get_text(strip=True)

                link_tag = article.find("a", href=True)
                if not link_tag:
                    continue
                hackathon_url = urljoin(url, link_tag["href"])

                # Extract dates if available
                date_tag = article.find("span", class_=re.compile("date|time"))
                date_text = date_tag.get_text(strip=True) if date_tag else "TBD"

                prize_tag = article.find("span", class_=re.compile("prize|award"))
                prize_text = prize_tag.get_text(strip=True) if prize_tag else "TBD"

                # Parse prize value
                prize_match = re.search(r"[\$\u00a5\u20ac\u00a3]([\d,]+)", prize_text)
                prize_value = int(prize_match.group(1).replace(",", "")) if prize_match else 0

                results.append({
                    "title": title,
                    "platform": "devpost",
                    "url": hackathon_url,
                    "location": "TBD",
                    "is_online": False,
                    "is_hybrid": True,
                    "themes": [],
                    "prize_pool": prize_text,
                    "currency": "USD",
                    "prize_value": prize_value,
                    "phases": [{"name": "Registration Deadline", "deadline": "TBD"}],
                    "sponsors": [],
                    "eligibility": "",
                    "status": "upcoming",
                    "date_range": date_text,
                    "added_at": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
                })
            except Exception as e:
                log(f"Error parsing Devpost card: {e}", "WARNING")
                continue

    except ImportError:
        log("requests and beautifulsoup4 required for scraping. "
            "Install: pip install requests beautifulsoup4", "WARNING")
    except Exception as e:
        log(f"Devpost scraping failed: {e}", "ERROR")

    log(f"Devpost: found {len(results)} hackathons")
    return results


def scrape_mlh() -> list[dict]:
    """
    Scrape upcoming hackathons from MLH (Major League Hacking).
    Uses their public events API if available, otherwise falls back to page parsing.
    """
    log("Scraping MLH...")
    results = []

    try:
        import requests

        # MLH has a JSON endpoint for their events
        url = "https://mlh.io/seasons/2026/events"
        headers = {"User-Agent": "Hackathon-DDL-Bot/1.0"}

        resp = requests.get(url, headers=headers, timeout=30)
        resp.raise_for_status()

        # Try to extract structured data from the page
        import re
        json_match = re.search(
            r"window\.__INITIAL_STATE__\s*=\s*({.+?});",
            resp.text,
        )
        if json_match:
            data = json.loads(json_match.group(1))
            for event in data.get("events", []):
                try:
                    results.append({
                        "title": event.get("name", "Unknown"),
                        "platform": "mlh",
                        "url": event.get("url", ""),
                        "location": event.get("location", "TBD"),
                        "is_online": event.get("virtual", False),
                        "is_hybrid": event.get("hybrid", False),
                        "themes": event.get("tags", []),
                        "prize_pool": "TBD",
                        "currency": "USD",
                        "prize_value": 0,
                        "phases": [{"name": "Registration Deadline", "deadline": "TBD"}],
                        "sponsors": [],
                        "eligibility": event.get("eligibility", ""),
                        "status": "upcoming",
                        "date_range": event.get("date", "TBD"),
                        "added_at": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
                    })
                except Exception as e:
                    log(f"Error parsing MLH event: {e}", "WARNING")
                    continue
        else:
            log("Could not find MLH initial state data", "WARNING")

    except ImportError:
        log("requests required for scraping", "WARNING")
    except Exception as e:
        log(f"MLH scraping failed: {e}", "ERROR")

    log(f"MLH: found {len(results)} hackathons")
    return results


def scrape_dorahacks() -> list[dict]:
    """
    Scrape hackathons from DoraHacks API.
    DoraHacks has a relatively open API.
    """
    log("Scraping DoraHacks...")
    results = []

    try:
        import requests

        # DoraHacks API endpoint for hackathons
        api_url = "https://dorahacks.io/api/hackathons"
        headers = {"User-Agent": "Hackathon-DDL-Bot/1.0"}

        resp = requests.get(api_url, headers=headers, timeout=30)
        if resp.status_code == 200:
            data = resp.json()
            for item in data.get("results", data if isinstance(data, list) else []):
                try:
                    results.append({
                        "title": item.get("name", "Unknown"),
                        "platform": "dorahacks",
                        "url": item.get("url", ""),
                        "location": item.get("location", "Online"),
                        "is_online": item.get("is_online", True),
                        "is_hybrid": item.get("is_hybrid", False),
                        "themes": item.get("tracks", []),
                        "prize_pool": item.get("prize", "TBD"),
                        "currency": item.get("currency", "USD"),
                        "prize_value": item.get("prize_usd", 0),
                        "phases": [{"name": "Registration Deadline", "deadline": "TBD"}],
                        "sponsors": item.get("sponsors", []),
                        "eligibility": item.get("eligibility", ""),
                        "status": "upcoming",
                        "date_range": item.get("date_range", "TBD"),
                        "added_at": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
                    })
                except Exception as e:
                    log(f"Error parsing DoraHacks event: {e}", "WARNING")
                    continue
        else:
            log(f"DoraHacks API returned status {resp.status_code}", "WARNING")

    except ImportError:
        log("requests required for scraping", "WARNING")
    except Exception as e:
        log(f"DoraHacks scraping failed: {e}", "ERROR")

    log(f"DoraHacks: found {len(results)} hackathons")
    return results


def merge_with_existing(
    scraped: list[dict], existing_dir: Path
) -> dict[str, list[dict]]:
    """
    Merge scraped data with existing YAML files.
    Returns dict mapping month filenames to merged data.
    """
    # Load all existing data
    existing: dict[str, dict] = {}
    for yml_file in sorted(existing_dir.glob("*.yml")):
        try:
            with open(yml_file, encoding="utf-8") as f:
                data = yaml.safe_load(f) or []
                for item in data:
                    if isinstance(item, dict) and "url" in item:
                        existing[item["url"]] = item
        except Exception as e:
            log(f"Error loading {yml_file}: {e}", "WARNING")

    log(f"Loaded {len(existing)} existing hackathons")

    # Merge scraped data - don't overwrite existing entries
    new_count = 0
    for item in scraped:
        url = item.get("url", "")
        if url and url not in existing:
            existing[url] = item
            new_count += 1

    log(f"Added {new_count} new hackathons")

    # Group by month based on first phase deadline
    by_month: dict[str, list[dict]] = {}
    for item in existing.values():
        phases = item.get("phases", [])
        if phases and phases[0].get("deadline") and phases[0]["deadline"] != "TBD":
            try:
                dt = datetime.fromisoformat(phases[0]["deadline"].replace("Z", "+00:00"))
                month_key = dt.strftime("%m_%b").lower()
            except (ValueError, TypeError):
                month_key = "unknown"
        else:
            month_key = "unknown"

        by_month.setdefault(month_key, []).append(item)

    return by_month


def create_failure_issue(error_msg: str):
    """Create a GitHub issue when scraping fails."""
    token = os.environ.get("GITHUB_TOKEN")
    repo = os.environ.get("GITHUB_REPOSITORY")
    if not token or not repo:
        log("No GitHub token/repo available for creating issue", "WARNING")
        return

    try:
        import requests

        url = f"https://api.github.com/repos/{repo}/issues"
        headers = {
            "Authorization": f"token {token}",
            "Accept": "application/vnd.github.v3+json",
        }
        data = {
            "title": f"[Scraper] Daily crawl failed - {datetime.now(timezone.utc).strftime('%Y-%m-%d')}",
            "body": (
                f"## Scraper Failure Report\n\n"
                f"**Time:** {datetime.now(timezone.utc).isoformat()}\n"
                f"**Error:** {error_msg}\n\n"
                f"### Manual intervention may be required.\n\n"
                f"cc: @maintainers"
            ),
            "labels": ["scraper", "automated", "needs-attention"],
        }
        resp = requests.post(url, headers=headers, json=data, timeout=30)
        if resp.status_code == 201:
            log(f"Created issue #{resp.json().get('number')}")
        else:
            log(f"Failed to create issue: {resp.status_code}", "WARNING")

    except Exception as e:
        log(f"Failed to create issue: {e}", "WARNING")


def main():
    parser = argparse.ArgumentParser(description="Hackathon-DDL Scraper")
    parser.add_argument("--output", default="data/2026", help="Output directory for YAML files")
    parser.add_argument("--dry-run", action="store_true", help="Don't write files, just log")
    args = parser.parse_args()

    output_dir = Path(args.output)
    output_dir.mkdir(parents=True, exist_ok=True)

    log("=" * 50)
    log("Hackathon-DDL Daily Scraper Starting")
    log("=" * 50)

    all_scraped: list[dict] = []
    errors: list[str] = []

    # Scrape each platform
    scrapers = [
        ("devpost", scrape_devpost),
        ("mlh", scrape_mlh),
        ("dorahacks", scrape_dorahacks),
    ]

    for name, scraper_fn in scrapers:
        try:
            results = scraper_fn()
            all_scraped.extend(results)
        except Exception as e:
            msg = f"{name} scraper crashed: {e}"
            log(msg, "ERROR")
            errors.append(msg)

    log(f"Total scraped: {len(all_scraped)} hackathons")

    if not all_scraped and errors:
        # All scrapers failed
        log("All scrapers failed! Creating issue...", "ERROR")
        create_failure_issue("; ".join(errors))
        sys.exit(1)

    # Merge with existing data
    by_month = merge_with_existing(all_scraped, output_dir)

    # Write output files
    if not args.dry_run:
        for month_key, items in sorted(by_month.items()):
            filename = f"{month_key}.yml"
            filepath = output_dir / filename
            write_yaml(items, filepath)

        log(f"Updated {len(by_month)} monthly YAML files")
    else:
        log("DRY RUN - no files written")
        for month_key, items in sorted(by_month.items()):
            log(f"Would write {len(items)} items to {month_key}.yml")

    log("=" * 50)
    log("Scraper completed successfully")
    log("=" * 50)


if __name__ == "__main__":
    main()
